# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: DataHelper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: docker://manifoldai/orbyter-ml-dev:2.0
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        pip install -r docker/requirements.txt
    - name: Test with pytest
      run: |
        pytest ./tests/test_dataHelpers.py
